# Generated by Django 6.0.6 on 2026-06-12 00:06

import cms.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCmsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('placeholder', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='cms_placeholder', to='cms.placeholder')),
            ],
        ),
    ]
