# Generated by Django 6.0.6 on 2026-06-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_customcmscontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCmsContent',
        ),
    ]
